### ISSUE TITLE
Body falls through the ground when killbind is used

### ISSUE THREAD

**Issue by MaxOhNoo** [Confusified/Lethal-Company-Mods#3]
Currently on default settings (unknown death, decapitation)

Your body falls through the map instantly after killbind.

**Comment by Confusified** [comment]
hey thanks for letting me know i'm looking into it now

**Comment by Confusified** [comment]
i'm uploading an updated version soon, let me know if it still happens when you have the time

**Comment by MaxOhNoo** [comment]
Interestingly, a similar mod called slashKill has the exact same problem. Simply dying next to the floor sends your body straight through.

I have a feeling this is a server-sided issue with how the bodies are created after death, but I’m no mod dev.

**Comment by Confusified** [comment]
oh that's interesting

if my patch fixes the issue then i could try to help the dev for that mod with this

i don't think it's a server-sided issue though, in my limited testing the body only goes under the map on the client and it's how it should be for the other players

**Comment by MaxOhNoo** [comment]
Thats weird. On experimentation (the moon) my friend couldn’t find my body
at all.

**Comment by MaxOhNoo** [comment]
Everything seems to function fine as of the recent patch.

**Comment by Confusified** [comment]
that's great, if anything changes let me know

**Comment by MaxOhNoo** [comment]
One thing of note is that bodies sometimes appear invisible to other people until picked up. However, this same issue occurred once when we were all vanilla, so this is more than likely a problem with LC itself.

**Comment by Confusified** [comment]
oh that's interesting i'll take note of that, though i have never seen that happen before yet
